### ISSUE TITLE
M-JPEG Stream with Mobotix Cameras

### ISSUE THREAD

**Issue by MaxPetermann** [rmja/MjpegRelay#1]
root@Kamera-Proxy:~/MjpegRelay/src/MjpegRelay# dotnet run -- --source=mjpeg --mjpeg:streamurl=http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full

The link works in Chrome Browser.

09.20.2022 14:15:41 info: MjpegRelay.StreamService[0]
      Connecting to stream
09.20.2022 14:15:41 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 14:15:41 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 14:15:41 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
09.20.2022 14:15:41 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
09.20.2022 14:15:41 info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
09.20.2022 14:15:41 info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
09.20.2022 14:15:41 info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/MjpegRelay/src/MjpegRelay/
09.20.2022 14:15:41 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 816.7455ms - 200
09.20.2022 14:15:41 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 825.2589ms - 200
09.20.2022 14:15:41 fail: MjpegRelay.StreamService[0]
      Stream error
      System.IO.InvalidDataException: Multipart body length limit 16384 exceeded.
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at MjpegRelay.MjpegSource.StreamAsync(CancellationToken cancellationToken) in /root/MjpegRelay/src/MjpegRelay/MjpegSource.cs:line 44
         at MjpegRelay.StreamService.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/StreamService.cs:line 21
^C09.20.2022 14:15:42 info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
09.20.2022 14:15:42 warn: MjpegRelay.Broadcaster[0]
      Something bad happened writing last image to clients.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at MjpegRelay.Broadcaster.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/Broadcaster.cs:line 59

dotnet --version
6.0.401

**Comment by rmja** [comment]
I hope that this is now fixed. I have published the fixed version to docker.

**Comment by MaxPetermann** [comment]
Thank you very much for your fast reply. Unfortunately, the problem is not solved yet.



root@Kamera-Proxy:~# rm -r MjpegRelay/
root@Kamera-Proxy:~# git clone https://github.com/rmja/MjpegRelay


Klone nach 'MjpegRelay' ...
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 85 (delta 43), reused 69 (delta 29), pack-reused 0
Empfange Objekte: 100% (85/85), 15.20 KiB | 15.20 MiB/s, fertig.
Löse Unterschiede auf: 100% (43/43), fertig.


root@Kamera-Proxy:~# cd MjpegRelay/src/MjpegRelay/
root@Kamera-Proxy:~/MjpegRelay/src/MjpegRelay# dotnet run -- --source=mjpeg --mjpeg:streamurl=http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full                                                                     09.20.2022 15:41:14 info: MjpegRelay.StreamService[0]/control/faststream.jpg?str                                                                                                                                                                   Connecting to stream
09.20.2022 15:41:14 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 15:41:14 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 15:41:14 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
09.20.2022 15:41:14 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
09.20.2022 15:41:14 info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
09.20.2022 15:41:14 info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
09.20.2022 15:41:14 info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/MjpegRelay/src/MjpegRelay/
09.20.2022 15:41:15 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 671.97ms - 200
09.20.2022 15:41:15 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 680.2017ms - 200
09.20.2022 15:41:15 fail: MjpegRelay.StreamService[0]
      Stream error
      System.IO.InvalidDataException: Multipart body length limit 16384 exceeded.
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at MjpegRelay.MjpegSource.StreamAsync(CancellationToken cancellationToken) in /root/MjpegRelay/src/MjpegRelay/MjpegSource.cs:line 49
         at MjpegRelay.StreamService.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/StreamService.cs:line 21
09.20.2022 15:41:16 info: MjpegRelay.StreamService[0]
      Connecting to stream
09.20.2022 15:41:16 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 15:41:16 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 15:41:16 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 638.8115ms - 200
09.20.2022 15:41:16 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 639.136ms - 200
09.20.2022 15:41:16 fail: MjpegRelay.StreamService[0]
      Stream error
      System.IO.InvalidDataException: Multipart body length limit 16384 exceeded.
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at MjpegRelay.MjpegSource.StreamAsync(CancellationToken cancellationToken) in /root/MjpegRelay/src/MjpegRelay/MjpegSource.cs:line 49
         at MjpegRelay.StreamService.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/StreamService.cs:line 21
09.20.2022 15:41:17 info: MjpegRelay.StreamService[0]
      Connecting to stream
09.20.2022 15:41:17 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 15:41:17 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
^C09.20.2022 15:41:18 info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
09.20.2022 15:41:18 warn: MjpegRelay.Broadcaster[0]
      Something bad happened writing last image to clients.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at MjpegRelay.Broadcaster.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/Broadcaster.cs:line 59
root@Kamera-Proxy:~/MjpegRelay/src/MjpegRelay# cd



root@Kamera-Proxy:~# docker pull rmjac/mjpeg-relay
Using default tag: latest
latest: Pulling from rmjac/mjpeg-relay
213ec9aee27d: Pull complete
c020f65418fd: Pull complete
b6e19b5e6f7f: Pull complete
aed8e91ef80d: Pull complete
9b8685c4d4c8: Pull complete
4f4fb700ef54: Pull complete
c0285b552bfe: Pull complete
Digest: sha256:1eb525394a525194580e08f71d6c5a90cac9cc0298d7ce8e2618924e8f1a86fa
Status: Downloaded newer image for rmjac/mjpeg-relay:latest
docker.io/rmjac/mjpeg-relay:latest



root@Kamera-Proxy:~# docker run --network=host rmjac/mjpeg-relay --urls=http://+:9000 --source=mjpeg --mjpeg:streamurl=http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09/20/2022 13:42:09 info: MjpegRelay.StreamService[0]
      Connecting to stream
09/20/2022 13:42:09 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09/20/2022 13:42:09 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09/20/2022 13:42:09 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:9000
09/20/2022 13:42:09 info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
09/20/2022 13:42:09 info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
09/20/2022 13:42:09 info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app/
09/20/2022 13:42:09 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 572.3995ms - 200
09/20/2022 13:42:09 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 582.786ms - 200
09/20/2022 13:42:09 fail: MjpegRelay.StreamService[0]
      Stream error
      System.IO.InvalidDataException: Multipart body length limit 16384 exceeded.
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at MjpegRelay.MjpegSource.StreamAsync(CancellationToken cancellationToken) in /src/src/MjpegRelay/MjpegSource.cs:line 49
         at MjpegRelay.StreamService.ExecuteAsync(CancellationToken stoppingToken) in /src/src/MjpegRelay/StreamService.cs:line 21
09/20/2022 13:42:10 info: MjpegRelay.StreamService[0]
      Connecting to stream
09/20/2022 13:42:10 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09/20/2022 13:42:10 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
^C09/20/2022 13:42:11 info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
09/20/2022 13:42:11 warn: MjpegRelay.Broadcaster[0]
      Something bad happened writing last image to clients.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at MjpegRelay.Broadcaster.ExecuteAsync(CancellationToken stoppingToken) in /src/src/MjpegRelay/Broadcaster.cs:line 59
root@Kamera-Proxy:~#

**Comment by rmja** [comment]
That is strange. I have increased the size of `HeaderLengthLimit` to 64k and according to the [MultipartReader source](https://github.com/dotnet/aspnetcore/blob/v6.0.0/src/Http/WebUtilities/src/MultipartReader.cs#L73) this is the field used when setting the initial body limit. Can you please verify that you are using the newest source?

**Comment by MaxPetermann** [comment]
I've got the newest source... 
Isn't it the `BodyLengthLimit` responsible for the crash?

`Multipart body length limit 16384 exceeded.`

**Comment by rmja** [comment]
It should be fixed now. I had to resort to reflection to assign the LengthLimit of _currentStream after it was created in the MultipartReader ctor. I have pushed the image to docker hub.

**Comment by MaxPetermann** [comment]
It still doesn't work...

root@Kamera-Proxy:~/MjpegRelay/src/MjpegRelay# dotnet run -- --source=mjpeg --mjpeg:streamurl=http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 19:58:21 info: MjpegRelay.StreamService[0]
      Connecting to stream
09.20.2022 19:58:21 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 19:58:21 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 19:58:21 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://0.0.0.0:5001
09.20.2022 19:58:21 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:5000
09.20.2022 19:58:21 info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
09.20.2022 19:58:21 info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
09.20.2022 19:58:21 info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/MjpegRelay/src/MjpegRelay/
09.20.2022 19:58:21 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 837.2291ms - 200
09.20.2022 19:58:21 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 846.5054ms - 200
09.20.2022 19:58:21 fail: MjpegRelay.StreamService[0]
      Stream error
      System.IO.InvalidDataException: Multipart body length limit 65536 exceeded.
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at MjpegRelay.MjpegSource.StreamAsync(CancellationToken cancellationToken) in /root/MjpegRelay/src/MjpegRelay/MjpegSource.cs:line 48
         at MjpegRelay.StreamService.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/StreamService.cs:line 21
09.20.2022 19:58:22 info: MjpegRelay.StreamService[0]
      Connecting to stream
09.20.2022 19:58:22 info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 19:58:22 info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request GET http://admin:<password>@192.168.20.134/control/faststream.jpg?stream=full
09.20.2022 19:58:23 info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 799.7686ms - 200
09.20.2022 19:58:23 info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 799.975ms - 200
09.20.2022 19:58:23 fail: MjpegRelay.StreamService[0]
      Stream error
      System.IO.InvalidDataException: Multipart body length limit 65536 exceeded.
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)
         at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
         at MjpegRelay.MjpegSource.StreamAsync(CancellationToken cancellationToken) in /root/MjpegRelay/src/MjpegRelay/MjpegSource.cs:line 48
         at MjpegRelay.StreamService.ExecuteAsync(CancellationToken stoppingToken) in /root/MjpegRelay/src/MjpegRelay/StreamService.cs:line 21
09.20.2022 19:58:24 info: MjpegRelay.StreamService[0]

**Comment by rmja** [comment]
But now the length limit has changed. Can you clone the source and increase the header length limit here: https://github.com/rmja/MjpegRelay/blob/master/src/MjpegRelay/MjpegSource.cs#L40

**Comment by MaxPetermann** [comment]
Exactly. I already tried increasing the limit to 4096. It seems to work, but it crashes after a few seconds...

**Comment by MaxPetermann** [comment]
I send you an email with direct link to the cam so you can test it yourself if you want.

**Comment by rmja** [comment]
Found the issue. It was not a buffer size problem. It was unable to find the boundary because it was quoted. I have fixed it now and pushed to docker hub.

**Comment by MaxPetermann** [comment]
Great job! It works now.

Thank you very much! :)
